fix save dir of dataset bugs
RUCAIBox/RecBole pull request #1087
Opened 2021-12-18 08:02 UTC by juyongjiang

To save filtered dataset and split dataloaders, I set parameter `save_dataset=True ` and parameter `save_dataloaders=True`, as suggested in [https://recbole.io/docs/user_guide/config/environment_settings.html](https://recbole.io/docs/user_guide/config/environment_settings.html). But it occurs some bugs which show that the directory of `self.config['checkpoint_dir']` does not exist. So I check the corresponding source code of `save` function to add a few lines of code to automatically make save dir if it does not exist. 

![0dc549cf75717892f3647fca6e940a6](https://user-images.githubusercontent.com/50765248/146634082-b4e82f66-d2cc-4600-86f5-fe9632ab2674.png)

2021-12-20 08:19 UTC, chenyushuo commented on recbole/data/dataset/dataset.py
> +            os.makedirs(save_dir)
```suggestion
        ensure_dir(self.config['checkpoint_dir'])
```
We have alread implemented `ensure_dir` function in `recbole.utils`. You can use this function to check directory existance and create it if it does not exist.

2021-12-20 08:19 UTC, chenyushuo commented on recbole/properties/overall.yaml
> +save_dataloaders: True
```suggestion
save_dataset: False
save_dataloaders: False
```
We don't recommend to set these parameters to `True` for disk space cost.

2021-12-20 08:21 UTC, chenyushuo requested changes
You can also fix the same bug in `recbole.data.utils.save_split_dataloaders` with `recbole.utils.ensure_dir`

2021-12-20 08:46 UTC, juyongjiang commented
> You can also fix the same bug in `recbole.data.utils.save_split_dataloaders` with `recbole.utils.ensure_dir`

That's great! Thank you! : )

2022-02-21 15:15 UTC, chenyushuo approved these changes

2022-02-21 15:16 UTC, merged