experments log enhance
RUCAIBox/RecBole pull request #1102
Opened 2022-01-04 12:40 UTC by MIracleyin

I made a lot of experments, it make log dir have many log file. 
Maybe using model name to category experments much better?

2022-01-04 12:41 UTC, MIracleyin commented
i am sorry, i update wrong message about "dataloader note"

2022-01-06 02:44 UTC, chenyushuo requested changes

2022-01-06 02:44 UTC, chenyushuo commented on recbole/data/dataloader/general_dataloader.py
> +            new_batch_size = batch_num * self.times # 最后 batch 有几个为
```suggestion
        if self.neg_sample_args['strategy'] == 'by':
            batch_num = max(batch_size // self.times, 1)
            new_batch_size = batch_num * self.times
```

2022-01-06 02:58 UTC, chenyushuo approved these changes

2022-01-06 02:59 UTC, merged