FEA: add SimpleX in general model
RUCAIBox/RecBole pull request #1282
Opened 2022-05-05 12:30 UTC by dreaming-qin

add SimpleX in general model

2022-05-10 01:37 UTC, Wicknight approved these changes

2022-05-10 01:43 UTC, Wicknight commented
@dreaming-qin Hello! Thanks for your attention to RecBole!
We have checked the code you submitted and found no problems. After that, we will conduct internal tests on various datasets. When the tests are completed, we will merge the code immediately. You are welcome to submit more codes to communicate with us.

2022-05-27 06:37 UTC, Wicknight requested changes

2022-05-27 06:37 UTC, Wicknight commented on recbole/model/general_recommender/simplex.py
> +        self.history_item_id, _, self.history_item_len = dataset.history_item_matrix()
在gpu运行时会报错，需要在这里添加self.history_item_id = self.history_item_id.to(self.device)以及self.history_item_len=self.history_item_len.to(self.device)

2022-05-27 06:37 UTC, Wicknight commented on recbole/model/general_recommender/simplex.py
> +        history_len = torch.minimum(history_len, torch.zeros(1)+self.history_len)
history_len=torch.minimum(history_len, torch.zeros(1, device=self.device)+self.history_len)

2022-05-27 06:37 UTC, Wicknight commented on recbole/model/general_recommender/simplex.py
> +        item_seq_len = torch.minimum(item_seq_len, torch.zeros(1)+self.history_len)
item_seq_len=torch.minimum(item_seq_len, torch.zeros(1, device=self.device)+self.history_len)

2022-05-27 06:37 UTC, Wicknight commented on recbole/model/general_recommender/simplex.py
> +        item_seq_len = torch.minimum(item_seq_len, torch.zeros(1)+self.history_len)
item_seq_len=torch.minimum(item_seq_len, torch.zeros(1, device=self.device)+self.history_len)

2022-05-27 09:18 UTC, dreaming-qin commented on recbole/model/general_recommender/simplex.py
> +        item_seq_len = torch.minimum(item_seq_len, torch.zeros(1)+self.history_len)
ok，已进行修改并已提交。除此之外还修改了predict方法与full_sort_predict方法的部分变量名称让变量更通俗易懂

2022-06-07 06:19 UTC, Wicknight approved these changes

2022-06-09 10:17 UTC, merged