FEA: Add FiGNN in Context Aware models
RUCAIBox/RecBole pull request #1509
Opened 2022-10-24 05:38 UTC by CIEEMio

2022-10-25 11:17 UTC, zhengbw0324 requested changes

2022-10-25 11:17 UTC, zhengbw0324 commented on recbole/model/context_aware_recommender/fignn.py
> +        self.mlp2 = nn.Sequential(
这里套一层nn.Sequential是多余的

2022-10-25 11:17 UTC, zhengbw0324 commented on recbole/model/context_aware_recommender/fignn.py
> +        self.loss = nn.BCELoss()
建议使用nn.BCEWithLogitsLoss()，可以参考一下其他context模型

2022-10-25 11:17 UTC, zhengbw0324 commented on recbole/model/context_aware_recommender/fignn.py
> +
完全copy参考代码建议标明

2022-11-06 03:08 UTC, zhengbw0324 requested changes

2022-11-06 03:08 UTC, zhengbw0324 commented on recbole/model/context_aware_recommender/fignn.py
> +
不是在文字里，是在代码里加一下`input_type = InputType.PAIRWISE`

2022-11-11 02:30 UTC, AoiDragon approved these changes

2022-11-11 03:38 UTC, zhengbw0324 approved these changes

2022-11-14 02:52 UTC, merged