FEA: add RaCT model
RUCAIBox/RecBole pull request #739
Opened 2021-02-27 13:33 UTC by Zephyr-29

2021-03-02 12:41 UTC, hyp1231 requested changes
(*To be discussed*) `Trainer._build_optimizer` may need to be refactored.

2021-03-02 12:41 UTC, hyp1231 commented on recbole/model/general_recommender/ract.py
> +    r"""RaCT is a item-based model collaborative filtering model that simultaneously rank all items for user .
Please use the expression in the original paper directly.

2021-03-02 12:41 UTC, hyp1231 commented on recbole/trainer/trainer.py
> +            raise ValueError("Please make sure that the 'train_stage' is 'pretrain' or 'finetune' ")
Two blank lines between classes.

```suggestion


            raise ValueError("Please make sure that the 'train_stage' is 'pretrain' or 'finetune' ")
```

2021-03-02 12:41 UTC, hyp1231 commented on recbole/model/general_recommender/ract.py
> +        return nn.Sequential(*mlp_modules)
Maybe `critic_layers_1/2/3` can be summarized into one single arg (e.g. [100, 100, 10]).

Then we can use a loop to construct critic layers.

2021-03-12 10:14 UTC, 2017pxy approved these changes

2021-03-12 14:27 UTC, 2017pxy approved these changes

2021-03-12 14:27 UTC, merged