[MODEL] Add SINE model
RUCAIBox/RecBole pull request #847
Opened 2021-06-18 08:39 UTC by Tokkiu

Add sequential model SINE from Alibaba
The paper is https://arxiv.org/abs/2102.09267

2021-06-18 08:42 UTC, 2017pxy commented
@Tokkiu Thx, we will review it as soon as possible.

2021-07-15 06:01 UTC, ChangxinTian requested changes
Thx.

2021-07-17 17:13 UTC, Tokkiu commented on recbole/model/sequential_recommender/sine.py
> +        return (torch.norm(C_reg) ** 2 - torch.norm(torch.diag(C_reg)) ** 2) / 2
ok, I will fix them

2022-02-17 02:26 UTC, ChangxinTian requested changes
Thanks for your reformation.

2022-02-17 03:31 UTC, Tokkiu commented on recbole/model/sequential_recommender/sine.py
> +        C_apt = F.softmax(torch.tanh(x_u_bar.matmul(self.w4)).matmul(self.w5), dim=1)
Thanks for your kind notice. I have changed them as same w3 as you can see in the latest commit.

2022-02-17 03:37 UTC, ChangxinTian approved these changes
Many thanks.

2022-02-20 05:38 UTC, 2017pxy commented
@Tokkiu hi，firstly thanks for your contribution!

In order to test your model, we removed your code into v1.0.x branch and add some docs for it (in #1142). After the test, we will merge them into master branch from v1.0.x branch and this model will be released in next version (maybe v1.0.1).  Thus, this PR will be closed and you are welcome to review the new PR（#1142）if you have time. Many thanks!

2022-02-20 05:48 UTC, Tokkiu commented
Dear Xingyu Pan,

Thank you for your kind notice. I think the code looks ok.

By the way, is there any thing or paper I can help to do further
implementation?

Best regards
Jingqi

Xingyu Pan ***@***.***> 于2022年2月20日周日 13:38写道：

> @Tokkiu <https://github.com/Tokkiu> hi，firstly thanks for your
> contribution!
>
> In order to test your model, we removed your code into v1.0.x branch and
> add some docs for it (in #1142
> <https://github.com/RUCAIBox/RecBole/pull/1142>). After the test, we will
> merge them into master branch from v1.0.x branch and this model will be
> released in next version (maybe v1.0.1). Thus, this PR will be closed and
> you are welcome to review the new PR（#1142
> <https://github.com/RUCAIBox/RecBole/pull/1142>）if you have time. Many
> thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RUCAIBox/RecBole/pull/847#issuecomment-1046167084>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADGLBK5SF4NBWGAM5KEAQYTU4B44LANCNFSM465HD3WA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-20 05:53 UTC, 2017pxy commented
@Tokkiu Hi, we have a discussion called new model to be added (#611 ), you can find one you are interested in and implement it.

2022-02-23 03:36 UTC, 2017pxy commented
This PR has been removed in #1142

2022-02-23 03:37 UTC, closed without merging