FEA: update the parameters of data filter
RUCAIBox/RecBole pull request #854
Opened 2021-06-25 02:57 UTC by ChangxinTian

2021-06-26 06:41 UTC, hyp1231 approved these changes
Others,

* `_analyse_intervals_str` or `_parse_intervals_str`, which one is better? (actually I'm not sure.)

2021-06-26 06:41 UTC, hyp1231 commented on recbole/data/dataset/dataset.py
> +            if not (len(endpoint_pair)==2 and left_bracket in ['(','['] and right_bracket in [')',']']):
```suggestion
            if not (len(endpoint_pair) == 2 and left_bracket in ['(', '['] and right_bracket in [')', ']']):
```

2021-06-26 06:41 UTC, hyp1231 commented on recbole/data/dataset/dataset.py
> +                if num_str in ["inf","-inf"]:
```suggestion
                if num_str in ["inf", "-inf"]:
```

2021-06-26 06:41 UTC, hyp1231 commented on recbole/data/dataset/dataset.py
> +            temp_result &= num<=right_point if right_bracket==']' else num<right_point
```suggestion
            temp_result = num >= left_point if left_bracket == '[' else num > left_point
            temp_result &= num <= right_point if right_bracket == ']' else num < right_point
```

2021-06-26 12:24 UTC, ChangxinTian commented
> Others,
> 
> * `_analyse_intervals_str` or `_parse_intervals_str`, which one is better? (actually I'm not sure.

`_parse_intervals_str` is better.
I will carefully check the code format in the future, thank you!

2021-06-29 02:48 UTC, chenyushuo requested changes

2021-06-29 02:48 UTC, chenyushuo commented on docs/source/user_guide/data/data_args.rst
> +- ``val_interval (dict)``: Has the format ``{k (str): interval (str), ...}``, where ``interval `` can be set as  ``[A,B]`` / ``[A,B)`` / ``(A,B)`` / ``(A,B]``. The rows whose ``feat[k]`` is in the in
``{k: [A,B);(C,D]}`` -> ``{k: "[A,B);(C,D]"}``

2021-06-29 02:48 UTC, chenyushuo commented on docs/source/user_guide/data/data_args.rst
> +- ``item_inter_num_interval (str)`` : Has the interval format, such as ``[A,B]`` / ``[A,B)`` / ``(A,B)`` / ``(A,B]``,  where ``A`` and ``B`` are the endpoints of the interval and ``A<B``. Items whose
``A<B`` -> ``A <= B``

2021-06-29 02:48 UTC, chenyushuo commented on recbole/data/dataset/dataset.py
> +            endpoint_pair = endpoint_pair_str.strip('[]()').split(',')
这里建议改成：
```python3
            endpoint_pair_str = endpoint_pair_str.strip()
            left_bracket, right_bracket = endpoint_pair_str[0], endpoint_pair_str[-1]
            endpoint_pair = endpoint_pair_str[1:-1].split(',')
```

2021-06-29 02:48 UTC, chenyushuo commented on recbole/data/dataset/dataset.py
> +                if num_str in ["inf", "-inf"]:
建议``num_str``改为``num_str.lower()``

2021-06-29 02:48 UTC, chenyushuo commented on recbole/data/dataset/dataset.py
> +        result = None
``result``的初值改为``True``，顺便修改下面的``result``更新表达式

2021-06-30 09:13 UTC, chenyushuo requested changes

2021-06-30 09:13 UTC, chenyushuo commented on recbole/data/dataset/dataset.py
> +                self.logger.warning( f'{endpoint_pair_str} is an illegal interval!')
这里多了一个空格

2021-06-30 09:13 UTC, chenyushuo commented on recbole/data/dataset/dataset.py
> +                    return np.inf if num_str == "inf" else -np.inf
这里也加一下 .lower()

2021-06-30 14:29 UTC, chenyushuo approved these changes

2021-06-30 14:29 UTC, merged