FIX: remove eval setting
RUCAIBox/RecBole pull request #862
Opened 2021-07-01 12:24 UTC by 2017pxy

2021-07-02 08:00 UTC, hyp1231 requested changes

2021-07-02 08:00 UTC, hyp1231 commented on recbole/data/dataset/sequential_dataset.py
> +            raise ValueError('The split_args in eval_args should not be None.')
```suggestion
```

2021-07-05 00:25 UTC, hyp1231 approved these changes

2021-07-05 00:46 UTC, chenyushuo approved these changes

2021-07-05 00:46 UTC, merged